name: spark
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [spark]
jobs:
  spark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ls -la  


