name: spark
on:
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [spark]
jobs:
  spark:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: temurin
    - uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.5.3'
        hadoop-version: '3'
    - run: spark-submit --version
    - run: spark-submit --version
    - run: spark-submit --master local hello.py
    - run: ls -la  
    - name: GIT commit and push docs
      env: 
        CI_COMMIT_MESSAGE: save spark results
        CI_COMMIT_AUTHOR: adsoft 
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "adsoft@live.com.mx"
        git add results
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push


